import pg from 'pg';
import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import { categories as defaultCategories, products as defaultProducts, sampleReviews as defaultReviews } from './seedData.js';
import { sampleOrders as defaultOrders } from './migrateAllToDb.js';

dotenv.config();

const { Client } = pg;

const SUPABASE_DATABASE_URL = process.env.SUPABASE_DATABASE_URL ||
  'postgresql://postgres.cuijbyfmtzulznxkpwgq:Aqeel%400419%23@aws-0-ap-south-1.pooler.supabase.com:5432/postgres';

async function run() {
  console.log('Connecting to Supabase PostgreSQL...');
  const pgClient = new Client({
    connectionString: SUPABASE_DATABASE_URL,
    ssl: { rejectUnauthorized: false }
  });

  await pgClient.connect();
  console.log('✓ Connected to Supabase PostgreSQL');

  console.log('Creating tables in Supabase...');

  // 1. Create tables
  await pgClient.query(`
    -- Categories
    CREATE TABLE IF NOT EXISTS categories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      slug VARCHAR(120) NOT NULL UNIQUE,
      description TEXT,
      image_url VARCHAR(500),
      display_order INT DEFAULT 0
    );

    -- Products
    CREATE TABLE IF NOT EXISTS products (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
      name VARCHAR(200) NOT NULL,
      slug VARCHAR(220) NOT NULL UNIQUE,
      brand VARCHAR(100) DEFAULT 'Yahiya Select',
      short_desc VARCHAR(300),
      description TEXT,
      price NUMERIC(10, 2) NOT NULL,
      stock INT NOT NULL DEFAULT 50,
      origin VARCHAR(100) DEFAULT 'Imported',
      cocoa_percentage INT DEFAULT 500,
      rating NUMERIC(2, 1) DEFAULT 4.8,
      reviews_count INT DEFAULT 12,
      is_featured BOOLEAN DEFAULT FALSE,
      is_new BOOLEAN DEFAULT FALSE,
      is_bestseller BOOLEAN DEFAULT FALSE,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Product Images
    CREATE TABLE IF NOT EXISTS product_images (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      image_url VARCHAR(500) NOT NULL,
      is_primary BOOLEAN DEFAULT FALSE
    );

    -- Users
    CREATE TABLE IF NOT EXISTS users (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(120) NOT NULL,
      email VARCHAR(180) NOT NULL UNIQUE,
      password_hash VARCHAR(255) NOT NULL,
      role VARCHAR(30) DEFAULT 'customer',
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Reviews
    CREATE TABLE IF NOT EXISTS reviews (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      user_name VARCHAR(120) NOT NULL,
      rating INT NOT NULL CHECK (rating >= 1 AND rating <= 5),
      title VARCHAR(200),
      comment TEXT,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Orders
    CREATE TABLE IF NOT EXISTS orders (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
      order_number VARCHAR(60) NOT NULL UNIQUE,
      customer_name VARCHAR(150) NOT NULL,
      customer_email VARCHAR(180) NOT NULL,
      customer_phone VARCHAR(50),
      total_amount NUMERIC(10, 2) NOT NULL,
      subtotal NUMERIC(10, 2) NOT NULL,
      tax_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
      shipping_fee NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
      discount_amount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
      promo_code VARCHAR(50) NULL,
      status VARCHAR(50) DEFAULT 'processing',
      payment_status VARCHAR(50) DEFAULT 'paid',
      payment_id VARCHAR(100) NULL,
      razorpay_order_id VARCHAR(100) NULL,
      shipping_address JSONB NOT NULL,
      created_at TIMESTAMPTZ DEFAULT NOW()
    );

    -- Order Items
    CREATE TABLE IF NOT EXISTS order_items (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
      product_id BIGINT NOT NULL,
      product_name VARCHAR(200) NOT NULL,
      quantity INT NOT NULL,
      unit_price NUMERIC(10, 2) NOT NULL,
      total_price NUMERIC(10, 2) NOT NULL,
      image_url VARCHAR(500)
    );

    -- Indexes for performance
    CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
    CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug);
    CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON product_images(product_id);
    CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON reviews(product_id);
    CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
    CREATE INDEX IF NOT EXISTS idx_orders_order_number ON orders(order_number);
    CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
  `);

  console.log('✓ Tables created.');

  // Enable Row Level Security and configure public access policies
  console.log('Configuring Row Level Security & permissions...');
  await pgClient.query(`
    ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
    ALTER TABLE products ENABLE ROW LEVEL SECURITY;
    ALTER TABLE product_images ENABLE ROW LEVEL SECURITY;
    ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;
    ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
    ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
    ALTER TABLE users ENABLE ROW LEVEL SECURITY;

    DO $$ BEGIN
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'categories' AND policyname = 'Allow public select on categories') THEN
        CREATE POLICY "Allow public select on categories" ON categories FOR SELECT USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'products' AND policyname = 'Allow public select on products') THEN
        CREATE POLICY "Allow public select on products" ON products FOR SELECT USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'product_images' AND policyname = 'Allow public select on product_images') THEN
        CREATE POLICY "Allow public select on product_images" ON product_images FOR SELECT USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reviews' AND policyname = 'Allow public select on reviews') THEN
        CREATE POLICY "Allow public select on reviews" ON reviews FOR SELECT USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'reviews' AND policyname = 'Allow public insert on reviews') THEN
        CREATE POLICY "Allow public insert on reviews" ON reviews FOR INSERT WITH CHECK (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'orders' AND policyname = 'Allow public insert on orders') THEN
        CREATE POLICY "Allow public insert on orders" ON orders FOR INSERT WITH CHECK (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'order_items' AND policyname = 'Allow public insert on order_items') THEN
        CREATE POLICY "Allow public insert on order_items" ON order_items FOR INSERT WITH CHECK (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'orders' AND policyname = 'Allow public select on orders') THEN
        CREATE POLICY "Allow public select on orders" ON orders FOR SELECT USING (true);
      END IF;
      IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'order_items' AND policyname = 'Allow public select on order_items') THEN
        CREATE POLICY "Allow public select on order_items" ON order_items FOR SELECT USING (true);
      END IF;
    END $$;

    GRANT USAGE ON SCHEMA public TO anon, authenticated;
    GRANT SELECT ON categories TO anon, authenticated;
    GRANT SELECT ON products TO anon, authenticated;
    GRANT SELECT ON product_images TO anon, authenticated;
    GRANT SELECT, INSERT ON reviews TO anon, authenticated;
    GRANT SELECT, INSERT ON orders TO anon, authenticated;
    GRANT SELECT, INSERT ON order_items TO anon, authenticated;
  `);

  console.log('✓ Row Level Security configured.');

  // Fetch data to migrate from MySQL or seedData fallback
  let categoriesToInsert = defaultCategories;
  let productsToInsert = defaultProducts;
  let usersToInsert = [];
  let ordersToInsert = defaultOrders;
  let reviewsToInsert = defaultReviews;

  try {
    const mysqlConn = await mysql.createConnection({
      host: process.env.DB_HOST || 'localhost',
      user: process.env.DB_USER || 'root',
      password: process.env.DB_PASSWORD || '',
      database: process.env.DB_NAME || 'chocolate_shop_db',
      port: Number(process.env.DB_PORT) || 3306
    });

    const [mysqlCats] = await mysqlConn.query('SELECT * FROM categories ORDER BY id ASC');
    if (mysqlCats.length > 0) categoriesToInsert = mysqlCats;

    const [mysqlProds] = await mysqlConn.query('SELECT * FROM products ORDER BY id ASC');
    if (mysqlProds.length > 0) {
      const [images] = await mysqlConn.query('SELECT * FROM product_images ORDER BY is_primary DESC, id ASC');
      const imgMap = new Map();
      for (const img of images) {
        const list = imgMap.get(img.product_id) || [];
        list.push(img.image_url);
        imgMap.set(img.product_id, list);
      }
      productsToInsert = mysqlProds.map(p => ({
        ...p,
        images: imgMap.get(p.id) || ['/images/products/ajwa-dates.jpg']
      }));
    }

    const [mysqlUsers] = await mysqlConn.query('SELECT * FROM users');
    if (mysqlUsers.length > 0) usersToInsert = mysqlUsers;

    const [mysqlOrders] = await mysqlConn.query('SELECT * FROM orders');
    if (mysqlOrders.length > 0) {
      const [orderItems] = await mysqlConn.query('SELECT * FROM order_items');
      const itemMap = new Map();
      for (const it of orderItems) {
        const list = itemMap.get(it.order_id) || [];
        list.push(it);
        itemMap.set(it.order_id, list);
      }
      ordersToInsert = mysqlOrders.map(o => ({
        ...o,
        items: itemMap.get(o.id) || []
      }));
    }

    const [mysqlReviews] = await mysqlConn.query('SELECT * FROM reviews');
    if (mysqlReviews.length > 0) reviewsToInsert = mysqlReviews;

    await mysqlConn.end();
    console.log(`✓ Fetched ${productsToInsert.length} products, ${categoriesToInsert.length} categories, and ${ordersToInsert.length} orders from local MySQL.`);
  } catch (err) {
    console.log('MySQL not available; using seed data fallback:', err.message);
  }

  // 2. Insert Categories
  for (const cat of categoriesToInsert) {
    await pgClient.query(`
      INSERT INTO categories (id, name, slug, description, image_url, display_order)
      VALUES ($1, $2, $3, $4, $5, $6)
      ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        slug = EXCLUDED.slug,
        description = EXCLUDED.description,
        image_url = EXCLUDED.image_url,
        display_order = EXCLUDED.display_order
    `, [cat.id, cat.name, cat.slug, cat.description, cat.image_url, cat.display_order]);
  }
  console.log(`✓ Migrated ${categoriesToInsert.length} categories.`);

  // 3. Insert Products & Images
  for (const p of productsToInsert) {
    await pgClient.query(`
      INSERT INTO products (
        id, category_id, name, slug, brand, short_desc, description,
        price, stock, origin, cocoa_percentage, rating, reviews_count,
        is_featured, is_new, is_bestseller
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
      ON CONFLICT (id) DO UPDATE SET
        category_id = EXCLUDED.category_id,
        name = EXCLUDED.name,
        slug = EXCLUDED.slug,
        brand = EXCLUDED.brand,
        short_desc = EXCLUDED.short_desc,
        description = EXCLUDED.description,
        price = EXCLUDED.price,
        stock = EXCLUDED.stock,
        origin = EXCLUDED.origin,
        cocoa_percentage = EXCLUDED.cocoa_percentage,
        rating = EXCLUDED.rating,
        reviews_count = EXCLUDED.reviews_count,
        is_featured = EXCLUDED.is_featured,
        is_new = EXCLUDED.is_new,
        is_bestseller = EXCLUDED.is_bestseller
    `, [
      p.id, p.category_id, p.name, p.slug, p.brand || 'Yahiya Select',
      p.short_desc || '', p.description || '', p.price, p.stock || 50,
      p.origin || 'Imported', p.cocoa_percentage || 500, p.rating || 4.8,
      p.reviews_count || 0, !!p.is_featured, !!p.is_new, !!p.is_bestseller
    ]);

    await pgClient.query('DELETE FROM product_images WHERE product_id = $1', [p.id]);
    const imgs = p.images || [];
    for (let i = 0; i < imgs.length; i++) {
      await pgClient.query(`
        INSERT INTO product_images (product_id, image_url, is_primary)
        VALUES ($1, $2, $3)
      `, [p.id, imgs[i], i === 0]);
    }
  }
  console.log(`✓ Migrated ${productsToInsert.length} products and images.`);

  // 4. Insert Admin & Customer Users
  const salt = await bcrypt.genSalt(10);
  const adminHash = await bcrypt.hash('Admin@123', salt);
  const customerHash = await bcrypt.hash('Customer@123', salt);

  const defaultUsers = [
    { id: 1, name: 'Yahiya Traders Admin', email: 'admin@yahiyatraders.com', password_hash: adminHash, role: 'admin' },
    { id: 2, name: 'Yahiya Traders Admin Alias', email: 'admin@chocolatier.com', password_hash: adminHash, role: 'admin' },
    { id: 3, name: 'Eleanor Vance', email: 'customer@example.com', password_hash: customerHash, role: 'customer' }
  ];

  const allUsers = usersToInsert.length > 0 ? usersToInsert : defaultUsers;
  for (const u of allUsers) {
    await pgClient.query(`
      INSERT INTO users (id, name, email, password_hash, role)
      VALUES ($1, $2, $3, $4, $5)
      ON CONFLICT (email) DO UPDATE SET
        name = EXCLUDED.name,
        password_hash = EXCLUDED.password_hash,
        role = EXCLUDED.role
    `, [u.id, u.name, u.email, u.password_hash || adminHash, u.role || 'customer']);
  }
  console.log(`✓ Migrated ${allUsers.length} users.`);

  // 5. Insert Reviews
  for (const r of reviewsToInsert) {
    await pgClient.query(`
      INSERT INTO reviews (product_id, user_name, rating, title, comment)
      SELECT $1::BIGINT, $2::VARCHAR, $3::INT, $4::VARCHAR, $5::TEXT
      WHERE NOT EXISTS (
        SELECT 1 FROM reviews WHERE product_id = $1::BIGINT AND user_name = $2::VARCHAR AND title = $4::VARCHAR
      )
    `, [r.product_id, r.user_name, r.rating, r.title, r.comment]);
  }
  console.log(`✓ Migrated ${reviewsToInsert.length} reviews.`);

  // 6. Insert Orders
  for (const o of ordersToInsert) {
    let shippingJson;
    try {
      if (typeof o.shipping_address === 'string') {
        JSON.parse(o.shipping_address);
        shippingJson = o.shipping_address;
      } else {
        shippingJson = JSON.stringify(o.shipping_address || {});
      }
    } catch {
      shippingJson = JSON.stringify({ address: o.shipping_address || '' });
    }

    const res = await pgClient.query(`
      INSERT INTO orders (
        order_number, user_id, customer_name, customer_email, customer_phone,
        total_amount, subtotal, tax_amount, shipping_fee, discount_amount,
        promo_code, status, payment_status, payment_id, razorpay_order_id, shipping_address
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
      ON CONFLICT (order_number) DO NOTHING
      RETURNING id
    `, [
      o.order_number, o.user_id || 1, o.customer_name, o.customer_email, o.customer_phone,
      o.total_amount, o.subtotal || o.total_amount, o.tax_amount || 0, o.shipping_fee || 0,
      o.discount_amount || 0, o.promo_code || null, o.status || 'processing',
      o.payment_status || 'paid', o.payment_id || null, o.razorpay_order_id || null,
      shippingJson
    ]);

    const orderId = res.rows[0]?.id;
    if (orderId && o.items) {
      for (const item of o.items) {
        await pgClient.query(`
          INSERT INTO order_items (order_id, product_id, product_name, quantity, unit_price, total_price, image_url)
          VALUES ($1, $2, $3, $4, $5, $6, $7)
        `, [
          orderId, item.product_id, item.product_name, item.quantity,
          item.unit_price, item.total_price || (item.quantity * item.unit_price),
          item.image_url || null
        ]);
      }
    }
  }
  console.log(`✓ Migrated ${ordersToInsert.length} orders.`);

  // Reset sequences so new items auto-increment properly
  await pgClient.query(`
    SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT MAX(id) FROM categories), 1));
    SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 1));
    SELECT setval(pg_get_serial_sequence('product_images', 'id'), COALESCE((SELECT MAX(id) FROM product_images), 1));
    SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
    SELECT setval(pg_get_serial_sequence('reviews', 'id'), COALESCE((SELECT MAX(id) FROM reviews), 1));
    SELECT setval(pg_get_serial_sequence('orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1));
    SELECT setval(pg_get_serial_sequence('order_items', 'id'), COALESCE((SELECT MAX(id) FROM order_items), 1));
  `);

  console.log('✓ Sequence auto-increment numbers updated.');

  // Verify total records in Supabase
  const counts = await pgClient.query(`
    SELECT
      (SELECT COUNT(*) FROM categories) as categories,
      (SELECT COUNT(*) FROM products) as products,
      (SELECT COUNT(*) FROM product_images) as images,
      (SELECT COUNT(*) FROM users) as users,
      (SELECT COUNT(*) FROM reviews) as reviews,
      (SELECT COUNT(*) FROM orders) as orders
  `);
  console.log('Final Supabase DB counts:', counts.rows[0]);

  await pgClient.end();
  console.log('✓ Migration to Supabase completed successfully!');
}

run().catch(err => {
  console.error('Migration failed:', err);
  process.exit(1);
});
