export const categories = [
  {
    id: 1,
    name: 'Royal Dates',
    slug: 'dates',
    description: 'Directly sourced royal dates: Authentic Medina Ajwa, King Medjoul, and Mabroom dates.',
    image_url: '/images/categories/dates.jpg',
    display_order: 1
  },
  {
    id: 2,
    name: 'Premium Nuts',
    slug: 'nuts',
    description: 'Crisp California almonds, giant W180 cashews, Kashmiri snow-white walnuts, and roasted crunchy peanuts.',
    image_url: '/images/categories/nuts.jpg',
    display_order: 2
  },
  {
    id: 3,
    name: 'Exotic Dry Fruits',
    slug: 'dry-fruits',
    description: 'Sun-dried Afghani figs (anjeer), natural orange slices, and golden Afghan raisins.',
    image_url: '/images/categories/dry-fruits.jpg',
    display_order: 3
  },
  {
    id: 4,
    name: 'Aromatic Spices',
    slug: 'spices',
    description: 'Hand-picked Green Cardamom 8.5mm, Tellicherry black pepper, Ceylon cinnamon, and Kashmiri saffron.',
    image_url: '/images/categories/spices.jpg',
    display_order: 4
  },
  {
    id: 5,
    name: 'Chocolates',
    slug: 'chocolates',
    description: 'Swiss Toblerone, crisp KitKat bars, and decadent European Belgian cocoa truffles.',
    image_url: '/images/categories/chocolates.jpg',
    display_order: 5
  },
  {
    id: 6,
    name: 'Nutrient Seeds',
    slug: 'seeds',
    description: 'Raw organic Chia seeds, roasted AAA pumpkin seeds, and shelled sunflower seeds.',
    image_url: '/images/categories/seeds.jpg',
    display_order: 6
  },
  {
    id: 7,
    name: 'Natural Herbs',
    slug: 'herbs',
    description: 'Sun-dried culinary Mediterranean mountain rosemary & thyme, and Greek oregano flakes.',
    image_url: '/images/categories/herbs.jpg',
    display_order: 7
  },
  {
    id: 8,
    name: 'Gourmet Snacks',
    slug: 'snacks',
    description: 'Crunchy peri-peri cashews, slow-roasted foxnut makhana, and wholesome artisan trail mix.',
    image_url: '/images/categories/snacks.jpg',
    display_order: 8
  }
];

export const products = [
  // 1. DATES VARIETIES
  {
    id: 1,
    category_id: 1,
    name: 'Royal Saudi Ajwa Al-Madinah Dates (500g)',
    slug: 'royal-saudi-ajwa-madinah-dates',
    brand: 'Yahya Royal',
    short_desc: 'Authentic Ajwa dates from the sacred groves of Medina. Soft, chewy & rich in minerals.',
    description: 'Revered worldwide as the crown jewel of dates. Sourced directly from certified date palm groves in Medina, Saudi Arabia. These Ajwa dates feature a deep black hue, tender texture, and a subtly sweet prune-like flavor profile. Packed with natural antioxidants, magnesium, and potassium.',
    price: 1250.00,
    stock: 45,
    origin: 'Medina, Saudi Arabia',
    cocoa_percentage: 500,
    rating: 4.9,
    reviews_count: 52,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/ajwa-dates.jpg']
  },
  {
    id: 2,
    category_id: 1,
    name: 'Medjoul King Dates Jumbo (500g)',
    slug: 'medjoul-king-dates-jumbo',
    brand: 'Yahya Select',
    short_desc: 'Colossal jumbo Medjoul dates with a luscious caramel-like honeyed sweetness.',
    description: 'Known as the "King of Dates", each hand-sorted Medjoul date boasts succulent, melt-in-the-mouth flesh with natural caramel undertones. Grown along the fertile Jordan valley, harvested at peak ripeness, and packed immediately for optimal moisture retention.',
    price: 990.00,
    stock: 65,
    origin: 'Jordan Valley',
    cocoa_percentage: 500,
    rating: 4.9,
    reviews_count: 38,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/medjoul-dates.jpg']
  },
  {
    id: 3,
    category_id: 1,
    name: 'Mabroom Royal Premium Dates (500g)',
    slug: 'mabroom-royal-premium-dates',
    brand: 'Yahya Reserve',
    short_desc: 'Slender, elongated chewy dates with a pleasant toffee flavor and rich chewiness.',
    description: 'Premium Mabroom dates sourced directly from Saudi Arabia. Renowned for their slender shape, firm yet pleasant chewiness, and delicate toffee undertones. Highly rich in dietary fiber and essential minerals.',
    price: 890.00,
    stock: 40,
    origin: 'Al-Qassim, Saudi Arabia',
    cocoa_percentage: 500,
    rating: 4.8,
    reviews_count: 24,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/mabroom-dates.jpg']
  },

  // 2. NUTS VARIETIES
  {
    id: 4,
    category_id: 2,
    name: 'California Almonds Premium Nonpareil (500g)',
    slug: 'california-almonds-premium-nonpareil',
    brand: 'Yahya Select',
    short_desc: 'Golden Californian Nonpareil almonds. Sweet, nutrient-dense, and naturally crunchy.',
    description: 'Supreme Grade Nonpareil almonds imported from California orchards. Naturally dried under the Mediterranean-style sun to lock in vitamin E, protein, and heart-healthy unsaturated fats. Uniform size, smooth skin, and sweet flavor.',
    price: 650.00,
    stock: 80,
    origin: 'California, USA',
    cocoa_percentage: 500,
    rating: 4.9,
    reviews_count: 58,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/california-almonds.jpg']
  },
  {
    id: 5,
    category_id: 2,
    name: 'King Jumbo W180 Roasted & Salted Cashews (500g)',
    slug: 'king-jumbo-w180-roasted-cashews',
    brand: 'Yahya Harvest',
    short_desc: 'Colossal king-grade W180 cashews, wood-fired roasted with pink Himalayan crystal salt.',
    description: 'Graded W180—the rarest and largest cashew grade harvested along coastal orchards. Each nut is carefully shelled, hand-sorted for uniform size, and slowly roasted in small batches. Seasoned with mineral-rich Himalayan pink salt for an unrivaled golden crunch.',
    price: 890.00,
    stock: 60,
    origin: 'Konkan Coast, India',
    cocoa_percentage: 500,
    rating: 4.8,
    reviews_count: 42,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/cashews-w180.jpg']
  },
  {
    id: 6,
    category_id: 2,
    name: 'Royal Kashmiri Snow-White Walnuts / Akhrot (500g)',
    slug: 'royal-kashmiri-snow-white-walnuts',
    brand: 'Yahya Harvest',
    short_desc: 'Kashmiri hand-cracked organic walnut kernels. Rich in brain-boosting Omega-3 and natural oils.',
    description: 'Hand-cracked premium walnut halves from the pristine high-altitude valleys of Kashmir. Naturally dried without chemicals or bleaching. Packed with alpha-linolenic acid (ALA) omega-3 fatty acids, antioxidants, and copper for heart and brain health.',
    price: 780.00,
    stock: 45,
    origin: 'Kashmir, India',
    cocoa_percentage: 500,
    rating: 4.9,
    reviews_count: 36,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    images: ['/images/products/walnuts.jpg']
  },
  {
    id: 25,
    category_id: 2,
    name: 'Bharuch Roasted & Salted Jumbo Peanuts (500g)',
    slug: 'bharuch-roasted-salted-jumbo-peanuts',
    brand: 'Yahya Harvest',
    short_desc: 'Classic sand-roasted jumbo Gujarat peanuts with a crisp, crunchy bite and golden sea salt.',
    description: 'Authentic traditional sand-roasted Bharuch jumbo peanuts. Roasted in small batches to golden perfection, lightly seasoned with fine salt. High in plant protein, dietary fiber, and vitamin E.',
    price: 290.00,
    stock: 75,
    origin: 'Gujarat, India',
    cocoa_percentage: 500,
    rating: 4.8,
    reviews_count: 40,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    images: ['/images/products/peanuts.jpg']
  },
  {
    id: 26,
    category_id: 2,
    name: 'Pistachio / Pista With Shell Roasted & Salted (500g)',
    slug: 'pistachio-pista-with-shell-salted',
    brand: 'Yahya Harvest',
    short_desc: 'Jumbo open-mouth pistachios roasted with light sea salt for an irresistible savory crunch.',
    description: 'Naturally opened jumbo pistachios, expertly dry roasted and sprinkled with fine sea salt. Packed with fiber, antioxidants, and vitamin B6. A nutritious anytime snack.',
    price: 920.00,
    stock: 55,
    origin: 'California / Turkey',
    cocoa_percentage: 500,
    rating: 4.8,
    reviews_count: 31,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/pistachios.jpg']
  },

  // 3. DRY FRUITS VARIETIES
  {
    id: 7,
    category_id: 3,
    name: 'Royal Afghani Sun-Dried Figs / Anjeer (500g)',
    slug: 'royal-afghani-sun-dried-figs-anjeer',
    brand: 'Yahya Reserve',
    short_desc: 'Naturally string-dried jumbo figs. Soft, juicy center with delightful crunchy seeds.',
    description: 'Hand-picked from the mountain orchards of Kandahar and naturally sun-dried on traditional strings. Plump, amber-hued, and exceptionally rich in calcium, iron, and dietary fiber without any added sugars.',
    price: 980.00,
    stock: 35,
    origin: 'Kandahar, Afghanistan',
    cocoa_percentage: 500,
    rating: 4.9,
    reviews_count: 27,
    is_featured: true,
    is_new: false,
    is_bestseller: false,
    images: ['/images/products/afghani-anjeer.jpg']
  },
  {
    id: 8,
    category_id: 3,
    name: 'Sun-Dried Natural Orange Slices (250g)',
    slug: 'sun-dried-natural-orange-slices',
    brand: 'Yahya Gourmet',
    short_desc: 'Vibrant, tangy, sun-dried citrus orange crisps. Wonderful for snacking, baking & tea infusions.',
    description: 'Thinly sliced ripe citrus oranges gently dehydrated to preserve intense aroma, natural zest, and high vitamin C. Delicious on their own, in mocktails, or alongside dark chocolates.',
    price: 490.00,
    stock: 30,
    origin: 'Spain',
    cocoa_percentage: 250,
    rating: 4.7,
    reviews_count: 19,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/orange-slices.jpg']
  },
  {
    id: 16,
    category_id: 3,
    name: 'Golden Afghan Kishmish Raisins (500g)',
    slug: 'golden-afghan-kishmish-raisins',
    brand: 'Yahya Reserve',
    short_desc: 'Long, slender golden raisins naturally sun-cured with luscious natural honey sweetness.',
    description: 'Prized Afghan Kishmish grown in the sunny valleys of Herat. Long, golden-amber dried grapes bursting with natural glucose, potassium, and antioxidants without sulfur or artificial glazes.',
    price: 420.00,
    stock: 50,
    origin: 'Herat, Afghanistan',
    cocoa_percentage: 500,
    rating: 4.8,
    reviews_count: 22,
    is_featured: false,
    is_new: true,
    is_bestseller: true,
    images: ['/images/products/golden-raisins.jpg']
  },

  // 4. SPICES VARIETIES
  {
    id: 12,
    category_id: 4,
    name: 'Cardamom 8.5mm Bold Green Pods (250g)',
    slug: 'cardamom-8-5mm-bold-green-pods',
    brand: 'Yahya Spices',
    short_desc: 'Extra-bold 8.5mm vibrant green cardamom pods harvested from high-altitude Idukki estates.',
    description: 'The highest grading of green cardamom available. Hand-picked from misty cardamom hills of Kerala. Bursting with aromatic essential oils, sweet floral fragrance, and fresh green color.',
    price: 850.00,
    stock: 50,
    origin: 'Idukki, Kerala, India',
    cocoa_percentage: 250,
    rating: 4.9,
    reviews_count: 29,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/cardamom-pods.jpg']
  },
  {
    id: 17,
    category_id: 4,
    name: 'Tellicherry Extra Bold Black Peppercorns (250g)',
    slug: 'tellicherry-bold-black-pepper',
    brand: 'Yahya Spices',
    short_desc: 'Jumbo sun-dried Malabar black peppercorns with intense pungent aroma and robust heat.',
    description: 'Estate-grown along the Malabar coastline, allowed to ripen longer on the vine for larger berry size and deeper essential oil concentration.',
    price: 380.00,
    stock: 45,
    origin: 'Tellicherry, Kerala',
    cocoa_percentage: 250,
    rating: 4.9,
    reviews_count: 18,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/black-pepper.jpg']
  },
  {
    id: 18,
    category_id: 4,
    name: 'Ceylon Pure True Cinnamon Quills (200g)',
    slug: 'ceylon-true-cinnamon-quills',
    brand: 'Yahya Spices',
    short_desc: 'Ultra-thin hand-rolled Ceylon cinnamon sticks with sweet woody fragrance and delicate layers.',
    description: 'Authentic Cinnamomum verum from Sri Lanka. Hand-rolled soft quills with delicate floral aroma and low coumarin levels, superior to ordinary cassia bark.',
    price: 490.00,
    stock: 35,
    origin: 'Sri Lanka',
    cocoa_percentage: 200,
    rating: 4.8,
    reviews_count: 15,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/cinnamon-quills.jpg']
  },
  {
    id: 19,
    category_id: 4,
    name: 'Royal Kashmiri Mongra Pure Saffron (2g)',
    slug: 'royal-kashmiri-mongra-saffron',
    brand: 'Yahya Spices',
    short_desc: 'Grade-A1 deep crimson Kashmiri Mongra saffron stigmas with rich golden coloring power.',
    description: 'Sourced from the saffron plateau of Pampore, Kashmir. 100% pure all-red Mongra threads with intoxicating aroma and rich crocin content.',
    price: 799.00,
    stock: 40,
    origin: 'Pampore, Kashmir',
    cocoa_percentage: 2,
    rating: 5.0,
    reviews_count: 36,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/saffron.jpg']
  },

  // 5. CHOCOLATES VARIETIES
  {
    id: 9,
    category_id: 5,
    name: 'Toblerone Swiss Milk Chocolate with Honey & Almond Nougat (300g)',
    slug: 'toblerone-swiss-milk-chocolate-nougat',
    brand: 'Toblerone Switzerland',
    short_desc: 'Iconic triangular Swiss milk chocolate packed with honey-almond nougat crunch.',
    description: 'Directly imported genuine Toblerone from Bern, Switzerland. Crafted with smooth Alpine milk chocolate, golden honey, and crunchy bits of almond nougat in the world-famous triangular peaks.',
    price: 540.00,
    stock: 75,
    origin: 'Bern, Switzerland',
    cocoa_percentage: 300,
    rating: 4.9,
    reviews_count: 64,
    is_featured: true,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/toblerone.jpg']
  },
  {
    id: 10,
    category_id: 5,
    name: 'KitKat 4-Finger Milk Chocolate Crisp (Pack of 6)',
    slug: 'kitkat-4-finger-milk-chocolate',
    brand: 'Nestlé Import',
    short_desc: 'Crispy wafer fingers layered in smooth European milk chocolate for the ultimate break.',
    description: 'Imported European KitKat with signature crisp oven-baked wafers enrobed in velvety milk chocolate. An all-time favorite treat for kids and adults alike.',
    price: 399.00,
    stock: 90,
    origin: 'United Kingdom',
    cocoa_percentage: 250,
    rating: 4.8,
    reviews_count: 45,
    is_featured: false,
    is_new: false,
    is_bestseller: false,
    images: ['/images/products/kitkat.jpg']
  },
  {
    id: 20,
    category_id: 5,
    name: 'Belgian Dark Chocolate Cocoa Truffles (250g)',
    slug: 'belgian-dark-chocolate-cocoa-truffles',
    brand: 'Yahya Confectionery',
    short_desc: 'Melt-in-the-mouth Belgian dark chocolate truffles dusted in rich bitter cocoa powder.',
    description: 'Authentic Belgian chocolate pralines filled with smooth chocolate ganache and lightly dusted with Dutch-processed cocoa powder.',
    price: 680.00,
    stock: 40,
    origin: 'Brussels, Belgium',
    cocoa_percentage: 250,
    rating: 4.9,
    reviews_count: 32,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    images: ['/images/products/belgian-truffles.jpg']
  },

  // 6. SEEDS VARIETIES
  {
    id: 13,
    category_id: 6,
    name: 'Raw Organic Mexican Chia Seeds (400g)',
    slug: 'organic-chia-seeds-pack',
    brand: 'Yahya Organics',
    short_desc: 'Superfood chia seeds loaded with plant omega-3, fiber, and calcium.',
    description: 'Certified 100% organic raw chia seeds. Ideal for puddings, smoothies, breakfast porridge, and bakery items.',
    price: 360.00,
    stock: 60,
    origin: 'Mexico',
    cocoa_percentage: 400,
    rating: 4.9,
    reviews_count: 33,
    is_featured: true,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/chia-seeds.jpg']
  },
  {
    id: 21,
    category_id: 6,
    name: 'Roasted AAA Green Pumpkin Seeds (400g)',
    slug: 'roasted-green-pumpkin-seeds',
    brand: 'Yahya Organics',
    short_desc: 'Crisp, roasted pepitas bursting with zinc, magnesium, and plant-based protein.',
    description: 'Grade AAA dark green pumpkin seed kernels, lightly dry roasted without oil. Nutty, crunchy, and packed with vital minerals.',
    price: 450.00,
    stock: 50,
    origin: 'India',
    cocoa_percentage: 400,
    rating: 4.8,
    reviews_count: 26,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/pumpkin-seeds.jpg']
  },
  {
    id: 22,
    category_id: 6,
    name: 'Shelled Golden Sunflower Seeds (400g)',
    slug: 'shelled-golden-sunflower-seeds',
    brand: 'Yahya Organics',
    short_desc: 'Nutrient-rich sunflower kernels, gently roasted with mild crunch and delicate nutty flavor.',
    description: 'Premium hulled sunflower seeds rich in vitamin E, selenium, and healthy fats. Delicious for snacking or topping salads.',
    price: 320.00,
    stock: 55,
    origin: 'Ukraine / India',
    cocoa_percentage: 400,
    rating: 4.7,
    reviews_count: 20,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/sunflower-seeds.jpg']
  },

  // 7. HERBS VARIETIES
  {
    id: 14,
    category_id: 7,
    name: 'Mediterranean Sun-Dried Mountain Rosemary & Thyme (150g)',
    slug: 'mediterranean-sun-dried-herbs-jar',
    brand: 'Yahya Botanical',
    short_desc: 'Aromatic hand-harvested wild rosemary, Greek oregano and mountain thyme in airtight glass jar.',
    description: 'Slow sun-cured Mediterranean botanicals selected from pesticide-free mountain slopes. Imparts intense pine-citrus aroma to roast potatoes, sourdough breads, pasta sauces, and infused olive oils.',
    price: 380.00,
    stock: 45,
    origin: 'Crete, Greece',
    cocoa_percentage: 150,
    rating: 4.8,
    reviews_count: 21,
    is_featured: false,
    is_new: true,
    is_bestseller: false,
    images: ['/images/products/rosemary-thyme.jpg']
  },
  {
    id: 23,
    category_id: 7,
    name: 'Organic Greek Mountain Oregano Flakes (150g)',
    slug: 'greek-mountain-oregano-flakes',
    brand: 'Yahya Botanical',
    short_desc: 'Pungent, sun-dried crushed wild oregano rich in aromatic thymol and essential oils.',
    description: 'Wild-harvested from high altitudes in Greece. Delivers authentic Mediterranean flavor to pizzas, pastas, salad dressings, and roasted vegetables.',
    price: 340.00,
    stock: 40,
    origin: 'Greece',
    cocoa_percentage: 150,
    rating: 4.9,
    reviews_count: 17,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/oregano.jpg']
  },

  // 8. SNACKS VARIETIES
  {
    id: 15,
    category_id: 8,
    name: 'Slow-Roasted Peri-Peri Cashews & Crunchy Foxnut Makhana (300g)',
    slug: 'roasted-peri-peri-cashews-makhana',
    brand: 'Yahya Gourmet Munchies',
    short_desc: 'Artisan wood-roasted jumbo cashews and crisp lotus seeds tossed in zesty African birds eye chili.',
    description: 'Guilt-free snacking perfection. Jumbo cashew kernels and popper-crisp makhana dry-roasted in small pans with virgin cold-pressed olive oil, smoked paprika, and fiery peri-peri spices.',
    price: 590.00,
    stock: 70,
    origin: 'Konkan & Bihar, India',
    cocoa_percentage: 300,
    rating: 4.9,
    reviews_count: 48,
    is_featured: true,
    is_new: true,
    is_bestseller: true,
    images: ['/images/products/periperi-cashews-makhana.jpg']
  },
  {
    id: 24,
    category_id: 8,
    name: 'Wholesome Artisan Roasted & Salted Trail Mix (400g)',
    slug: 'artisan-roasted-salted-trail-mix',
    brand: 'Yahya Gourmet Munchies',
    short_desc: 'Handcrafted crunch mix with California almonds, cashews, pumpkin seeds, and dried cranberries.',
    description: 'The ultimate energy blend. Lightly sea-salted dry roasted almonds, jumbo cashews, crunchy pumpkin seeds, and tart ruby cranberries.',
    price: 520.00,
    stock: 65,
    origin: 'Global Blend',
    cocoa_percentage: 400,
    rating: 4.9,
    reviews_count: 39,
    is_featured: false,
    is_new: false,
    is_bestseller: true,
    images: ['/images/products/trail-mix.jpg']
  }
];

export const sampleReviews = [
  {
    product_id: 1,
    user_name: 'Dr. Zeeshan Farooqui',
    rating: 5,
    title: 'Pure authentic Medina Ajwa! Outstanding quality',
    comment: 'The Ajwa dates were fresh, tender, and came in pristine luxury vacuum packaging. Tastes exactly like what we get directly from Saudi Arabia. Yahya Traders has become our family go-to.'
  },
  {
    product_id: 2,
    user_name: 'Priyanka Saxena',
    rating: 5,
    title: 'The Medjoul dates are colossal and melt in your mouth',
    comment: 'Biggest dates I have ever seen online in India! Naturally sweet, soft as caramel, and perfect for morning breakfast smoothies and healthy snacking.'
  },
  {
    product_id: 5,
    user_name: 'Rohan Mehta',
    rating: 5,
    title: 'Crispy, jumbo cashews with perfect Himalayan salt',
    comment: 'Not a single broken piece in the 500g pouch. The wood-roasted aroma and crunch are unmatched. Shipped within 24 hours just as advertised!'
  },
  {
    product_id: 9,
    user_name: 'Ananya Deshmukh',
    rating: 5,
    title: 'Genuine imported Toblerone! Loved the packaging',
    comment: 'Arrived in temperature-controlled protective bubble wrap without any melting. Real Swiss taste with lots of honey nougat.'
  }
];
